name: Generate Dependency Graphs
on:
  workflow_dispatch:
    push:
      branches: [ main ]

env:
  DOT_OUTPUT: 'images/dependencies.dot'
  GRAPH_OUTPUT: 'images/dependencies.svg'

jobs:
  dependency_graphs:
    name: Dependency Graphs
    runs-on: macos-12
    steps:
    - name: Git Checkout main
      uses: actions/checkout@v3

    - name: Install Graphviz
      run: brew install graphviz

    -  name: Show Dependencies
       run: |
          NO_DEPENDENCY_MESSAGE="No external dependencies found"

          for dir in Packages/*/ ; do
              out=${dir}$GRAPH_OUTPUT
              dot=${dir}$DOT_OUTPUT
              swift package --package-path $dir show-dependencies --format dot -o $dot
              if ! grep -q $NO_DEPENDENCY_MESSAGE "$dot"; then
                  dot -Tsvg $dot > $out
              fi
          done

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update package dependency graphs
